import { ArticleSection } from "../ConceptArticle";
import { Article, Cite } from "../AiStackConceptPageShared";
import { agentLoopSources } from "@/lib/ai-stack-concept-sources/agent-loop";
import { AgentLoopLesson } from "../ai-stack-lessons/agent-loop";
import { AgentLoopSignatureHero } from "../AgentLoopSignatureHero";

export function AgentLoopTermPage() {
  const sections: [string, string][] = [["loop-story", "先看一张失败的任务单"], ["loop-turn", "一次只做一个动作"], ["loop-state-chapter", "结果怎样改写下一轮"], ["loop-stop", "停止不等于成功"]];
  return <Article slug="agent-loop" title="智能体循环" subtitle="Agent Loop · 让一次动作的结果决定下一步" sources={agentLoopSources} sections={sections} hero={<AgentLoopSignatureHero />} intro={<>智能体循环像一张会回到桌面的任务单：先读当前状态，做一个受控动作，等外部结果回来，再决定继续、修正还是停下。没有“结果写回”和“什么时候停”，反复调用工具也只是重复按按钮。</>}>
    <ArticleSection id="loop-story" title="先看一张失败的任务单"><p>周五发布前，服务的健康检查还在返回 500。任务单上写着一件很具体的事：把服务修到 <code>GET /health → 200 OK</code>。第一眼能看到的不是“模型要思考几步”，而是当前状态里还有一个问题：<code>API_BASE_URL</code> 没有配置。</p><p id="loop-runner" className="vp-citation-target">Runner 接到起始输入后会循环调用模型；如果模型给出最终答案就结束，如果请求工具或 handoff，运行器执行并把结果追加回输入，再进入下一轮。也就是说，工具结果不是旁白，它是下一轮判断的材料。<Cite id="loop-runner" sources={agentLoopSources} /></p><AgentLoopLesson /></ArticleSection>
    <ArticleSection id="loop-turn" title="一次只做一个动作"><p id="loop-reason-act" className="vp-citation-target">ReAct 论文把“推理”和“行动”交替起来：先根据当前信息选一个动作，再观察环境回来的结果。落到工程里，最小的可观察单位可以是一次 <code>run_checks()</code>：发出时状态还是“待检查”，返回后才知道是 200、500 还是工具错误。<Cite id="loop-reason-act" sources={agentLoopSources} /></p><p>所以“修代码、跑测试、宣布完成”不应被压成一句黑盒描述。把动作和结果分开，读者才能看出模型是在等待工具、处理失败证据，还是已经拿到了可以结束的信号；应用也才能在权限、超时或人工确认处停住。</p></ArticleSection>
    <ArticleSection id="loop-state-chapter" title="结果怎样改写下一轮"><p id="loop-workflow" className="vp-citation-target">如果工具返回 <code>500 · missing API_BASE_URL</code>，下一轮的状态就不该仍写着“还有一个未知问题”。它至少要保存错误类别、关联动作和待修复项。Anthropic 把固定流程和更自主的 agent 分开讨论；越开放的循环，越需要把环境结果、检查器和人工边界放在能被观察的位置。<Cite id="loop-workflow" sources={agentLoopSources} /></p><p id="loop-orchestration" className="vp-citation-target">编排器可以让模型选择下一个工具，也可以由代码规定“先检查配置，再重跑健康检查”。两者的共同点是：每个动作都要有输入和可验收的回执。OpenAI Agents SDK 的多智能体编排文档也把 handoff、agent-as-tool 等选择放在流程设计里，而不是把它们当成循环本身。<Cite id="loop-orchestration" sources={agentLoopSources} /></p><p id="loop-state" className="vp-citation-target">采用状态图或检查点时，保存的是“现在走到哪个节点、带着哪些输入”。恢复运行后仍要重新确认外部世界：服务可能已经回滚、文件可能被别人改过、权限可能已经过期。LangGraph 把持久化和恢复作为运行时能力，这不等于替系统完成业务验证。<Cite id="loop-state" sources={agentLoopSources} /></p></ArticleSection>
    <ArticleSection id="loop-stop" title="停止不等于成功"><p id="loop-limit" className="vp-citation-target">循环至少要有两种出口：健康检查真的返回 200，或者已经达到允许的轮数。Agents SDK 用 <code>max_turns</code> 限制循环；到达上限会抛出 <code>MaxTurnsExceeded</code>，任务仍可以明确标记为未完成，而不是把“停止”改写成“成功”。<Cite id="loop-limit" sources={agentLoopSources} /></p><p>失败、取消和超时也应各自留下证据。若工具没有返回、权限被拒绝或人工撤销动作，状态应该告诉用户停在了哪里；下一次恢复时，先从这份状态出发，再决定是否重试，而不是偷偷重复可能有副作用的动作。</p><p><strong>判断一条循环是否可靠</strong>：能否说出每一轮读到的状态？动作的结果是否真的改变了状态？成功、失败、取消和轮数上限能否在界面上区分？这三问都答不上来时，看到的多半只是“模型又调用了一次工具”。</p></ArticleSection>
  </Article>;
}
