import { ArticleSection, ArticleAside, ConceptTerm } from "../ConceptArticle";
import { Article, Cite } from "../AiStackConceptPageShared";
import { agentMemorySources } from "@/lib/ai-stack-concept-sources/agent-memory";
import { AgentMemoryLesson } from "../ai-stack-lessons/agent-memory";
import { AgentMemoryHero } from "../ai-stack-lessons/agent-memory-hero";

export function AgentMemoryTermPage() {
  const sections: [string, string][] = [["memory-message", "一句话先是当前消息"], ["memory-record", "写进去的是记录，不是整段聊天"], ["memory-insert", "取回来还要送进本轮"], ["memory-control", "纠正和删除影响未来"]];
  return <Article slug="agent-memory" title="智能体记忆" subtitle="Agent Memory · 为后续任务保存并取回的信息" sources={agentMemorySources} sections={sections} hero={<AgentMemoryHero />} intro={<>下午的聊天里，用户随口说了一句“以后代码示例优先用 TypeScript”。这句话能不能留到下次，取决于应用怎样征得同意、写下记录、按任务取回，再把它交给模型使用。</>}>
    <ArticleSection id="memory-message" title="一句话先是当前消息"><p>这句话可以影响眼前的回答，却不等于已经进入下一次会话。产品若想把它留下，应先告诉用户保存什么、用于什么范围，并让用户明确同意；没有同意时，当前对话仍可以照着 TypeScript 回答，结束后就到此为止。</p><p id="memory-definition" className="vp-citation-target">LangChain 把跟着线程走的短期记忆和跨会话的长期记忆分开：前者属于当前对话的状态，后者要由应用通过持久化 store 保存和取回。所谓“记住”，首先是应用选定了一个保存范围。<Cite id="memory-definition" sources={agentMemorySources} /></p></ArticleSection>
    <ArticleSection id="memory-record" title="写进去的是记录，不是整段聊天"><p>得到同意后，应用也不必把整段聊天打包。它可以只留下一个窄窄的条目：<code>代码示例用 TypeScript</code>，来源是用户，范围是代码任务，附上更新时间和失效规则。旁边那条“食谱少放盐”仍然可以存在，但写代码时不该顺手一起拿出来。</p><p id="memory-scope" className="vp-citation-target">长期记忆通常需要 namespace 或其他归属信息，把用户、组织、项目和用途分开；LangChain 的 store 以 namespace 和 key 组织 JSON 记录，也支持按内容和范围检索。记录有归属，取回才有边界。<Cite id="memory-scope" sources={agentMemorySources} /></p><p id="memory-write" className="vp-citation-target">记忆可以在当前请求的“热路径”里写入，也可以交给后台任务处理。前者更快让新偏好生效，也更容易让用户看见保存发生了什么；后者减少当前请求的等待，但要另定什么时候写、写了什么。<Cite id="memory-write" sources={agentMemorySources} /></p><AgentMemoryLesson /></ArticleSection>
    <ArticleSection id="memory-insert" title="取回来还要送进本轮"><p>新会话说“请给我一个登录接口示例”时，应用先从两条记录里筛出代码偏好，再把这一条放进本轮输入。取回动作本身只是应用拿到了资料；只有放进输入，模型才会在这次回答里看见它。</p><p id="memory-selection" className="vp-citation-target">Anthropic 把上下文工程描述为持续挑选本轮真正有用的信息：面对不断增长的历史和外部材料，系统要保持高信号、低噪声，不能把整个记忆库倾倒给模型。<Cite id="memory-selection" sources={agentMemorySources} /></p><p id="memory-session" className="vp-citation-target">OpenAI Agents SDK 的 session 会在每次运行前取回会话历史，并在运行后保存新消息；它处理的是会话状态持久化，仍由应用判断哪些事实适用，以及用户能否查看、纠正或删除。<Cite id="memory-session" sources={agentMemorySources} /></p><ArticleAside title="三种东西各在一层"><p><ConceptTerm slug="context">上下文</ConceptTerm>是这一次真正交给模型的材料；<ConceptTerm slug="agent-memory">记忆</ConceptTerm>是应用以后可以取回的材料；模型训练得到的通用知识又在另一层。把一条记录保存到数据库，不会改写模型参数，也不能保证它已经参与当前回答。</p></ArticleAside></ArticleSection>
    <ArticleSection id="memory-control" title="纠正和删除影响未来"><p>用户后来发现自己想改用 Python，可以把记录纠正为 Python。已经生成的 TypeScript 示例仍然是过去发生的输出，不会被回头改写；下一个符合范围的任务才会看到新记录。</p><p id="memory-reflection" className="vp-citation-target">Generative Agents 研究把记忆记录、检索、反思和计划接成长期行为，说明“有记忆”还包含怎样从记录中挑出值得使用的内容；这是一个研究系统的设计，不是所有产品都会自动反思或永久保存。<Cite id="memory-reflection" sources={agentMemorySources} /></p><p id="memory-virtual" className="vp-citation-target">MemGPT 用分层记忆管理有限上下文，通过在快层和慢层之间移动信息来延长可用上下文。它提醒我们：外部存储可以很大，但每一轮仍要选择搬进来的内容。<Cite id="memory-virtual" sources={agentMemorySources} /></p><p><strong>边界</strong>：删除是未来取回的控制，不是历史回答的橡皮擦。涉及个人或敏感内容时，还要把访问权限、保留期限、删除入口和审计记录写成产品规则。</p></ArticleSection>
  </Article>;
}
