import { ArticleSection } from "../ConceptArticle";
import { Article, Cite } from "../AiStackConceptPageShared";
import { contextWindowSources } from "@/lib/ai-stack-concept-sources/context-window";
import { ContextWindowLesson } from "../ai-stack-lessons/context-window";
import { ContextWindowHero } from "../ai-stack-lessons/context-window-hero";

export function ContextWindowTermPage() {
  const sections: [string, string][] = [["window-story", "先跟着一段聊天看"], ["window-budget", "答案还没写，位置已经要留"], ["window-prune", "整理不是无损搬家"], ["window-boundary", "装得下也要找得准"]];
  return <Article slug="context-window" title="上下文窗口" subtitle="Context Window · 这一轮请求能带进来的工作空间" sources={contextWindowSources} sections={sections} hero={<ContextWindowHero />} intro={<>你在聊天里说过的话，不会自动变成模型这一轮永远可用的“记忆”。每次请求都要重新准备一块有限的工作空间：旧消息、规则、工具结果和还没生成的回答一起进来，也一起占位置。</>}>
    <ArticleSection id="window-story" title="先跟着一段聊天看"><p>周末出游时，你先说“周六出发”，接着发了民宿地址，又聊了十几页天气。最后真正要问的是：“帮我排一个行程，周日 17:00 前必须到家。”如果应用把整段聊天原样塞给模型，最早那句出发时间、最后那条回家约束，都会和天气闲聊争同一块空间。</p><p id="context-token-count" className="vp-citation-target">这里的 <strong>token</strong> 不是简单的字数，也不是页面上的字符数；具体模型会按自己的分词规则把文本、格式和其他输入拆成 token。要知道这一轮究竟用了多少，应该用目标模型提供的计数接口或读取响应里的 usage，而不是凭眼睛估算。<Cite id="context-token-count" sources={contextWindowSources} /></p><p id="context-state" className="vp-citation-target">应用可以把多轮消息手动拼起来，也可以借助会话标识继续一段对话；无论采用哪种状态管理，发出下一次请求时都要形成一份实际输入。聊天记录存在哪里，和这一次请求带了哪些内容，是两件事。<Cite id="context-state" sources={contextWindowSources} /></p><ContextWindowLesson /></ArticleSection>
    <ArticleSection id="window-budget" title="答案还没写，位置已经要留"><p id="context-budget" className="vp-citation-target">把窗口想成一张要同时摆餐具和菜的餐桌：系统规则、用户消息、检索结果和工具回执先占输入位置，模型还需要一块地方写答案。OpenAI 的说明把输入、输出，以及某些模型的推理 token 都放在同一个 context window 约束里；输入越长，能留下的输出空间就越少。<Cite id="context-budget" sources={contextWindowSources} /></p><p id="context-output" className="vp-citation-target">所以“还差一点点就满了”并不只是页面显示拥挤。若回答预留不够，结果可能被截断；若把工具返回的整张表都带上，真正要回答的那一句反而没有余量。教学演示里的 16k 只是方便看出先后关系，线上应以具体模型的上限和实际 token 统计为准。<Cite id="context-output" sources={contextWindowSources} /></p></ArticleSection>
    <ArticleSection id="window-prune" title="整理不是无损搬家"><p id="context-session" className="vp-citation-target">会话工具能帮应用找回上一轮的消息，却不会替应用决定哪些内容仍然值得带进来。Agents SDK 的 session 负责保存和取回运行历史；当历史越来越长，应用仍要在下一轮前选择摘要、裁剪、检索，或把旧工具结果留在窗口外。<Cite id="context-session" sources={contextWindowSources} /></p><p id="context-overflow" className="vp-citation-target">窗口放不下时，平台可能拒绝请求，也可能按照自身策略截短输入；Claude 的文档把这种超限行为和自动 compaction 单独列出来。无论是谁替你裁，结果都不是“模型看到了全部内容”：被移出的“周日 17:00 前到家”如果没有进入摘要，就已经不再是这一轮可依据的条件。<Cite id="context-overflow" sources={contextWindowSources} /></p><p id="context-compaction" className="vp-citation-target">压缩也不是把原文缩小后原封不动保存。Anthropic 建议在长任务里保留目标、关键决定、未完成动作和必要证据，并在压缩后重新检查这些字段；这正是旅行例子里应该留下的四件事，而不是把每次天气闲聊都平均写进摘要。<Cite id="context-compaction" sources={contextWindowSources} /></p><p id="context-selection" className="vp-citation-target">做整理前先问三个问题：这条事实会不会改变下一步？它有没有可验证的来源？删掉它后，模型还能复原用户的约束吗？答案都是否定时，才适合把它移到外部记录或直接丢弃。<Cite id="context-selection" sources={contextWindowSources} /></p></ArticleSection>
    <ArticleSection id="window-boundary" title="装得下也要找得准"><p id="context-attention" className="vp-citation-target">Transformer 的注意力机制允许模型在不同位置之间建立关系，但“能放进去”不等于“每个位置都同样容易被用到”。输入的顺序、重复的提示和干扰材料，都会影响模型从中找出哪条信息。<Cite id="context-attention" sources={contextWindowSources} /></p><p id="context-utilization" className="vp-citation-target">“Lost in the Middle” 的实验观察到，关键信息放在长上下文中间时，模型的利用效果可能低于把它放在开头或结尾。旅行计划里，最容易被淹没的正是夹在十页天气聊天里的返程限制；把它提到摘要开头、在最终任务旁再写一次，是内容组织的选择，不是增加窗口大小。<Cite id="context-utilization" sources={contextWindowSources} /></p><p>因此，排查“模型怎么又忘了”时，按这个顺序看：第一，统计本轮实际 token；第二，标出必须保留的约束和回答预留；第三，检查摘要或裁剪是否把关键事实改写掉；最后才考虑是否需要检索或分段处理。窗口解决的是“能不能带进来”，上下文编排还要解决“带进来后能不能找到”。</p></ArticleSection>
  </Article>;
}
