import test from 'node:test';
import assert from 'node:assert/strict';
import { initialBooks, runStatement, statement, applyMigration, initialOrm, changeObject } from '../lib/query-teaching.ts';
test('SQL row scope, migration history gates and ORM flush/commit boundaries', () => {
  const rows = initialBooks();
  const query = runStatement(rows,'select',true);
  assert.equal(query.rows, rows); assert.deepEqual(query.result.map(x=>x.id),[42]);
  assert.equal(runStatement(rows,'update',true).rows[1].available,false);
  assert.equal(runStatement(rows,'update',true).message,'UPDATE 1 · 更新 1 行');
  assert.equal(runStatement(rows,'update',false).message,'UPDATE 2 · 更新 2 行');
  assert.deepEqual(runStatement(rows,'delete',true).rows.map(x=>x.id),[78]);
  assert.equal(runStatement(rows,'delete',false).rows.length,0);
  assert.equal(runStatement([],'delete',true).message,'DELETE 0 · 删除 0 行');
  const inserted=runStatement(rows,'insert',true).rows;
  assert.equal(runStatement(inserted,'insert',true).rows,inserted);
  assert.equal(inserted.length,3); assert.equal(rows.length,2);
  assert.ok(!statement('delete',false).includes('WHERE'));
  const start={revision:1,oldApp:true};
  assert.equal(applyMigration(start,4).state,start);
  const two=applyMigration(start,2).state,three=applyMigration(two,3).state;
  assert.equal(applyMigration(three,2).state,three);
  assert.equal(applyMigration(three,4).state,three);
  assert.equal(applyMigration({...three,oldApp:false},4).state.revision,4);
  const object=initialOrm(),edited=changeObject(object,'edit'),flushed=changeObject(edited,'flush');
  assert.equal(edited.trace.length,2); assert.equal(edited.committed,'山间来信');
  assert.equal(flushed.flushed,edited.object); assert.equal(flushed.committed,'山间来信');
  assert.equal(changeObject(flushed,'flush').trace.length,4);
  const rollback=changeObject(flushed,'rollback'); assert.equal(rollback.object,null);
  assert.equal(changeObject(rollback,'reload').object,'山间来信');
  const committed=changeObject(edited,'commit'); assert.equal(committed.object,null);
  assert.equal(committed.committed,edited.object); assert.equal(committed.trace.at(-1),'COMMIT');
  assert.equal(changeObject(committed,'reload').object,edited.object);
  assert.equal(changeObject(committed,'edit'),committed);
});
