export const harnessSectionTitles = {
  why: "1. 先看只有模型时，会发生什么",
  need: "2. 谁让模型真的动手？",
  name: "3. 为什么叫 Harness？",
  practice: "4. 用“磁盘为什么满了”走一遍",
  boundary: "5. 一句“我要读日志”，中间到底发生了什么？",
  tools: "6. Tool 是什么？它和 Harness 怎么分？",
  inside: "7. 先认清这六样东西",
  service: "8. 现在，再让它修好一个服务",
  quality: "9. 同一个模型，为什么换一套 Harness 就可能不同？",
  compare: "10. 最后分清 Model、Harness 和 Agent",
  code: "再往里看：循环可以写成什么样？",
  roadmap: "接下来怎么学",
  check: "两道小题",
  related: "相关词条",
} as const;
