import { Archive, ArrowDown, ArrowRight, FileText, Globe, LockSimple, PencilLine, PlugsConnected, Terminal } from "@phosphor-icons/react/dist/ssr";
import { ConceptHero } from "./ConceptHero";
import styles from "./ExtendedConcepts.module.css";

export function MemoryHero() { return <ConceptHero slug="memory" label="进度写入外部存储，新会话再取回"><div className={styles.memoryHero}><div className={styles.archiveBack}><Archive size={28} weight="light" /><span>项目记忆</span></div><div className={styles.archiveNote}><FileText size={19} /><span>待检查 /health</span></div><div className={styles.newSession}>新会话 <ArrowDown size={17} /> 取回进度</div></div></ConceptHero>; }
export function WindowHero() { return <ConceptHero slug="context-window" label="有限窗口内，输入与输出共同占用容量"><div className={styles.windowHero}><span>上下文窗口</span><div className={styles.miniCapacity}><i /><i /><i /></div><div className={styles.capacityKey}><span>输入</span><span>输出</span></div><span className={styles.windowBracket}>容量不变 · 内容变化</span></div></ConceptHero>; }
export function PromptHero() { return <ConceptHero slug="prompt" label="把模糊的请求改写成有材料与要求的任务"><div className={styles.promptHero}><PencilLine size={23} /><del>帮我看看</del><div><span>依据启动日志</span><strong>指出错误位置</strong><span>给出修改与检查方法</span></div></div></ConceptHero>; }
export function McpHero() { return <ConceptHero slug="mcp" label="应用通过 MCP 客户端连接到服务器提供的能力"><div className={styles.mcpHero}><div><Terminal size={28} weight="light" /><span>应用</span></div><PlugsConnected className={styles.plugHero} size={40} weight="light" /><div className={styles.capabilitiesHero}><span>Tools</span><span>Resources</span><span>Prompts</span></div></div></ConceptHero>; }
export function SandboxHero() { return <ConceptHero slug="execution-sandbox" label="操作留在许可范围内，越界访问被阻止"><div className={styles.sandboxHero}><div><Terminal size={28} weight="light" /><span>/workspace</span><ArrowRight className={styles.boundaryArrow} size={28} /></div><LockSimple size={25} className={styles.boundaryLock} /><Globe className={styles.outsideGlobe} size={31} weight="light" /></div></ConceptHero>; }
