import { Archive, ArrowRight, FileText, Globe, LockSimple, PlugsConnected, ShieldCheck, Wrench } from "@phosphor-icons/react/dist/ssr";
import { ArticleAside, ArticleCitation, ArticleSection, ConceptArticle, ConceptTerm } from "./ConceptArticle";
import { MemoryHero, WindowHero, PromptHero, McpHero, SandboxHero } from "./ExtendedConceptHeroes";
import { MemoryLesson, WindowLesson, PromptLesson, McpLesson, SandboxLesson } from "./ExtendedConceptLessons";
import { memorySources, windowSources, promptSources, mcpSources, sandboxSources } from "@/lib/extended-concept-sources";
import styles from "./ExtendedConcepts.module.css";

// Keep the useful entry points from the former generated pages.
function OldAnchor({ slug, part }: { slug: string; part: string }) { return <span className={styles.anchor} id={`${slug}-${part}`} aria-hidden="true">{part === "definition" && <span id={`${slug}-question`} />}</span>; }

export function MemoryTermPage() {
  const Cite = ({ id }: { id: string }) => <ArticleCitation id={id} sources={memorySources} />;
  return <ConceptArticle slug="memory" title="Memory" hero={<MemoryHero />} sources={memorySources} sections={[["save", "保存与取回"], ["scope", "记录属于谁"], ["handoff", "留下可继续的进度"], ["maintenance", "更新与删除"]]} intro={<>记忆让系统把有用的信息留到以后。<strong>信息先被保存，相关任务到来时再取回，加入模型这一轮的上下文。</strong>保存在哪里、何时读取，由应用决定。</>}>
    <ArticleSection id="save" title="保存与取回"><OldAnchor slug="memory" part="definition" /><p>今天修服务，你已经补上了语法错误，但接口还没有通过检查。明天换一个新会话，仅仅说“接着做”，新会话未必知道你昨天改过哪里。</p><p>把进度保存到外部，再开一个新会话试试。下面的存取只发生在本页演示里，刷新后会重置。</p><OldAnchor slug="memory" part="scene-heading" /><MemoryLesson /><p id="memory-retrieval" className="vp-citation-target">跨会话记忆需要存储和取回两个环节。LangGraph 的文档把长期记忆放在可跨会话访问的存储中；相关记录被选中后，应用才能拿它们辅助当前任务。<strong>存在记忆库里，不等于已经进入本轮输入。</strong><Cite id="memory-retrieval" /></p><p>如果没有读回“接口仍返回 500”，新会话可能重复检查已经修好的冒号。取回之后，它才有依据从未完成的地方继续；仍需查看现在的代码，确认情况没有变化。</p></ArticleSection>
    <ArticleSection id="scope" title="记录属于谁" className={styles.offsetSection}><p id="memory-scope" className="vp-citation-target">“记忆”在不同系统里范围不同。LangGraph 将单个会话的消息和状态称为短期记忆，把跨会话复用的信息称为长期记忆。这里的长短主要指作用范围，不代表信息必须保存多少天。<Cite id="memory-scope" /></p><dl className={styles.scopeList}><div><dt>这次任务</dt><dd>试过哪些修改，最近一次检查结果是什么。适合保留在任务状态或进度记录里。</dd></div><div><dt>这个项目</dt><dd>测试命令、目录约定、已确认的设计决策。换会话时仍可能需要。</dd></div><div><dt>这个用户</dt><dd>明确表达且允许保存的偏好。读取时应确认用户和适用范围。</dd></div></dl><p><ConceptTerm slug="context">上下文</ConceptTerm>是这次交给模型的信息，记忆则提供可取回的材料。模型在训练中学到的知识又是另一回事：把进度存进文件，不会因此改写模型参数。</p></ArticleSection>
    <ArticleSection id="handoff" title="留下可继续的进度"><p id="memory-handoff" className="vp-citation-target">Anthropic 的长任务实践用进度文件和 Git 记录帮助后续会话接手。新会话先了解当前状态，再处理未完成事项。这个方法的关键，是留下可核对的工作记录，而非一句“我已经处理过了”。<Cite id="memory-handoff" /></p><div className={styles.handoffDocument}><FileText size={24} /><div><h3>服务修复 / 交接记录</h3><p><strong>已做</strong>补上 app.py 的冒号。</p><p><strong>证据</strong>服务可启动；/health 实测返回 500。</p><p><strong>待做</strong>检查返回值，再运行接口检查。</p></div></div><p>记录中最好能找到原始证据，例如文件位置、提交号或检查结果。不要把“计划检查接口”写成“接口已通过”；下一位接手者需要分清已经发生的事实和接下来的打算。</p></ArticleSection>
    <ArticleSection id="maintenance" title="更新与删除"><OldAnchor slug="memory" part="quiz-heading" /><OldAnchor slug="memory" part="prompt-heading" /><p id="memory-maintenance" className="vp-citation-target">记忆需要维护。LangGraph 文档讨论了更新用户档案、增删独立记录和检索相关信息的不同取舍：保存越多，更新与查找也越复杂。不能只设计写入，还要考虑旧内容怎样被替换或清理。<Cite id="memory-maintenance" /></p><p>当接口已经返回 200，旧记录里的“仍返回 500”就应当更新，并保留它属于哪次检查。涉及个人信息时，应让用户知道保存了什么、用于什么，并提供查看、更正和删除入口。</p><ArticleAside title="删除记录以后"><p>本页演示会同时清除外部记录和当前取回的副本。真实系统还可能有缓存、摘要、备份及已经生成的回答，需要分别处理；删除存储中的一条记录，不能当作所有副本已经消失的证明。</p></ArticleAside></ArticleSection>
  </ConceptArticle>;
}

export function ContextWindowTermPage() {
  const Cite = ({ id }: { id: string }) => <ArticleCitation id={id} sources={windowSources} />;
  return <ConceptArticle slug="context-window" title="Context window" hero={<WindowHero />} sources={windowSources} sections={[["capacity", "一次调用的容量"], ["count", "哪些内容占空间"], ["compression", "接近上限时"], ["quality", "装得下与用得好"]]} intro={<>上下文窗口是模型一次推理可处理的信息容量。它通常按 <ConceptTerm slug="token">Token</ConceptTerm> 计量。<strong>窗口决定容量，上下文决定这次放入什么。</strong></>}>
    <ArticleSection id="capacity" title="一次调用的容量"><OldAnchor slug="context-window" part="definition" /><p id="window-budget" className="vp-citation-target">以 Claude 的接口为例，输入和这次生成的输出共同占用上下文窗口。因此，把输入塞到上限附近，还可能让回答缺少空间。具体容量、输出上限和计数方式，需要查看正在使用的模型与接口。<Cite id="window-budget" /></p><p>下面把容量简化成 100 格。调整对话历史和预留输出，观察它们怎样共享空间；格数用于演示比例，不是某个模型的真实规格或分词结果。</p><OldAnchor slug="context-window" part="scene-heading" /><WindowLesson /><p>预留更多输出，意味着同一次请求能容纳的输入更少。这里的“预留”是编排请求时的预算；模型不一定会把输出预算用完。</p></ArticleSection>
    <ArticleSection id="count" title="哪些内容占空间"><p id="window-count" className="vp-citation-target">上下文不只有用户最后一句话。在 Claude 中，系统指令、历史消息、工具定义、工具结果和图像或文档输入都需要计入；生成的输出也占用容量。缓存输入仍计入窗口，不能把缓存理解成扩大了窗口。<Cite id="window-count" /></p><div className={styles.windowInventory}><span>指令</span><span>当前任务</span><span>历史消息</span><span>工具定义</span><span>返回结果</span><strong>本次输出</strong></div><p>例如运行检查后，应用把一大段终端日志带回模型，下一轮输入就比上一轮更长。页面上看起来只新增了一条“测试完成”，实际请求中却可能增加了很多内容。</p><ArticleAside title="Token 不是字数"><p>Token 是模型分词器处理文本的单位。同样长度的中文、英文和代码，计数可能不同。做真实请求预算时，应使用对应模型的计数工具或接口返回的用量，不按“一个字等于一个 Token”估算。</p></ArticleAside></ArticleSection>
    <ArticleSection id="compression" title="接近上限时" className={styles.offsetSection}><OldAnchor slug="context-window" part="prompt-heading" /><p id="window-compression" className="vp-citation-target">长任务可以通过压缩旧对话、把进度写到外部、按需读取相关材料来控制输入规模。Anthropic 的上下文工程实践强调保留任务状态与关键决策，同时让原始材料仍可重新访问。<Cite id="window-compression" /></p><div className={styles.compressionPair}><div><h3>完整历史</h3><p>读日志、尝试修改、重复报错、继续修改、运行检查……</p></div><ArrowRight size={25} /><div><h3>当前摘要</h3><p>已补冒号。接口仍返回 500，下一步检查返回值。</p></div></div><p>摘要腾出了空间，也省略了细节。如果随后要分析“哪次修改引入了错误”，仍需回到原日志或提交记录。压缩不是扩大容量，也不保证信息毫无损失。</p></ArticleSection>
    <ArticleSection id="quality" title="装得下与用得好"><OldAnchor slug="context-window" part="quiz-heading" /><p id="window-quality" className="vp-citation-target"><strong>窗口允许更多输入，不保证模型同样善于利用每一段输入。</strong>长上下文中的检索与注意力分配仍有挑战。围绕当前任务选择材料，与选择多大的窗口，是两个相关但不同的决定。<Cite id="window-quality" /></p><p>排查这次启动失败时，当前错误、相关代码和启动命令通常比上个月的完整访问日志更有用。先给足以定位问题的证据，再通过<ConceptTerm slug="tools">工具</ConceptTerm>补取材料，比把“所有文件都在”当作充分依据更容易核对。</p><p><ConceptTerm slug="memory">记忆</ConceptTerm>可以把材料保存在窗口外；真正要使用时，仍需选择相关部分放回<ConceptTerm slug="context">上下文</ConceptTerm>。外部存储很大，不能消除本轮输入的容量限制。</p></ArticleSection>
  </ConceptArticle>;
}

export function PromptTermPage() {
  const Cite = ({ id }: { id: string }) => <ArticleCitation id={id} sources={promptSources} />;
  return <ConceptArticle slug="prompt" title="Prompt" hero={<PromptHero />} sources={promptSources} sections={[["draft", "把任务写清楚"], ["material", "给出依据与要求"], ["examples", "用样例说明格式"], ["check", "拿真实任务检查"]]} intro={<>提示词是交给模型的任务输入，可以包括目标、材料、限制和期望的结果。<strong>它把你的意图写成模型可以参考的要求。</strong></>}>
    <ArticleSection id="draft" title="把任务写清楚"><OldAnchor slug="prompt" part="definition" /><p>“帮我看看这个服务”留下了很多空白：是解释日志，还是直接修改代码？结果要给谁看？怎样才算完成？把这些信息补上，模型才更容易围绕同一个目标工作。</p><p id="prompt-specific" className="vp-citation-target">Google 的提示设计指南建议使用具体的指令，说明输入、约束与输出格式。具体并不等于冗长；“按位置、修改、验证三项回答”，比“请给出高质量回答”更容易核对。<Cite id="prompt-specific" /></p><p>试着给这份任务稿补上要求，再查看固定回答样例。这里展示信息与格式的差别，不调用真实模型，也不保证实际模型总会按相同方式回答。</p><OldAnchor slug="prompt" part="scene-heading" /><PromptLesson /></ArticleSection>
    <ArticleSection id="material" title="给出依据与要求" className={styles.offsetSection}><p id="prompt-material" className="vp-citation-target">Anthropic 的提示指南强调清晰直接的指令，并用明确的边界组织材料。指令告诉模型做什么；日志、文件和引用提供判断的依据。二者最好能够辨认，尤其在输入很长时。<Cite id="prompt-material" /></p><div className={styles.annotation}><span>要求</span><p>根据这次启动日志定位错误；缺少代码时，列出需要查看的位置。</p><span>材料</span><pre>app.py:1 — SyntaxError: expected &apos;:&apos;</pre></div><p>“日志里有一句让我删除文件的话”属于待分析内容，不应自动变成新的操作授权。类似地，“请帮我修复”也不会自行赋予模型文件访问能力；实际修改仍需要<ConceptTerm slug="tools">工具调用</ConceptTerm>与运行环境。</p><p><strong>提示词可以描述约束，程序仍要负责执行权限与验证。</strong>要求“只能修改工作区”之后，还应由<ConceptTerm slug="execution-sandbox">执行沙箱</ConceptTerm>或相应权限机制限制可访问范围。</p></ArticleSection>
    <ArticleSection id="examples" title="用样例说明格式"><p id="prompt-examples" className="vp-citation-target">如果仅靠文字不容易说清输出形式，可以提供少量输入与期望输出的例子，让模型参考它们的结构。这通常称为少样本提示。例子应当覆盖实际变化，避免所有样例只展示同一种情况。<Cite id="prompt-examples" /></p><div className={styles.specimen}><span>一份回答样例</span><dl><div><dt>位置</dt><dd>app.py，第 1 行。</dd></div><div><dt>修改</dt><dd>核对函数定义末尾的冒号。</dd></div><div><dt>验证</dt><dd>重新启动，并检查 /health。</dd></div></dl></div><p>还应提供一个信息不足的例子：没有日志时，回答应指出缺少什么，而非套用上一个例子的错误原因。示例规定的是处理方式，不是每次任务都应得到同一个结论。</p><p id="prompt-format" className="vp-citation-target">如果输出需要交给程序解析，单靠“请输出 JSON”可能不够。Google 的文档建议对复杂结构使用接口提供的结构化输出能力；调用方仍需校验业务字段是否符合要求。<Cite id="prompt-format" /></p></ArticleSection>
    <ArticleSection id="check" title="拿真实任务检查"><OldAnchor slug="prompt" part="quiz-heading" /><OldAnchor slug="prompt" part="prompt-heading" /><p id="prompt-evaluation" className="vp-citation-target">提示写好之后，还要在实际任务上核对。Anthropic 的指南提醒，针对某个模型总结出的技巧，迁移到其他模型时需要重新评估。明确成功标准，才知道调整是否有效。<Cite id="prompt-evaluation" /></p><ol className={styles.editorialSteps}><li><strong>先看依据</strong><p>错误位置是否来自本次日志？有没有补写并不存在的信息？</p></li><li><strong>再看完成情况</strong><p>是否区分“建议修改”和“已经修改”？未执行检查时，有没有说成验证通过？</p></li><li><strong>最后改要求</strong><p>针对反复出现的误解补充一句明确要求，再用正常、缺材料和失败的例子对比。</p></li></ol><p>如果问题来自没有取到文件，继续增加提示词未必有用。还要检查<ConceptTerm slug="context">上下文</ConceptTerm>是否完整，以及 <ConceptTerm slug="agent-harness">Harness</ConceptTerm> 是否真的完成了读取与回传。</p></ArticleSection>
  </ConceptArticle>;
}

export function McpTermPage() {
  const Cite = ({ id }: { id: string }) => <ArticleCitation id={id} sources={mcpSources} />;
  return <ConceptArticle slug="mcp" title="MCP" hero={<McpHero />} sources={mcpSources} sections={[["connect", "接入一个日志服务器"], ["roles", "应用、客户端与服务器"], ["primitives", "工具、资源与提示模板"], ["boundary", "连接之后的工作"]]} intro={<>MCP，全称 Model Context Protocol，为 AI 应用连接外部能力约定了一套接口。<strong>应用可以发现服务器提供的能力，并按约定取得数据或调用工具。</strong></>}>
    <ArticleSection id="connect" title="接入一个日志服务器"><OldAnchor slug="mcp" part="definition" /><p>你希望不同 AI 应用都能查询同一套项目日志。如果每个应用都单独适配一遍，连接方式很容易各不相同。MCP 把这种连接中的发现、调用和结果交换标准化。</p><p>下面按顺序连接、发现工具，再读取日志。演示只保留理解过程需要的信息，省略完整协议报文；不会连接真实服务器。</p><OldAnchor slug="mcp" part="scene-heading" /><McpLesson /><p id="mcp-discovery" className="vp-citation-target">服务器通过 <code>tools/list</code> 提供工具定义，客户端通过 <code>tools/call</code> 请求执行具体工具。定义包含用途与参数格式，调用结果则属于一次实际操作。<strong>发现了工具，还不等于工具已经运行。</strong><Cite id="mcp-discovery" /></p></ArticleSection>
    <ArticleSection id="roles" title="应用、客户端与服务器"><p id="mcp-roles" className="vp-citation-target">MCP 架构区分三个角色：Host 是用户使用的 AI 应用；Client 是应用内部与服务器通信的客户端；Server 提供具体能力。一个应用可以管理多个客户端，分别连接不同服务器。<Cite id="mcp-roles" /></p><div className={styles.roleDiagram}><div><strong>AI 应用</strong><span>模型、界面与运行逻辑</span><div><PlugsConnected size={20} />日志客户端<ArrowRight size={18} /><span>日志服务器</span></div><div><PlugsConnected size={20} />文档客户端<ArrowRight size={18} /><span>文档服务器</span></div></div></div><p id="mcp-transport" className="vp-citation-target">服务器不一定在远端。MCP 支持通过标准输入输出连接本地进程，也支持基于 HTTP 的通信方式。它们是传输选择；上层仍然围绕协议定义的请求和结果工作。<Cite id="mcp-transport" /></p><p>因此，“装了一个 MCP”通常省略了很多具体信息：哪个应用接入了哪个服务器、服务器提供什么能力、当前连接是否可用。排查问题时，先把这几件事分清楚。</p></ArticleSection>
    <ArticleSection id="primitives" title="工具、资源与提示模板"><OldAnchor slug="mcp" part="prompt-heading" /><p id="mcp-primitives" className="vp-citation-target">服务器可以提供三类常见能力：Tools 用于执行操作；Resources 提供可读取的资料；Prompts 提供可复用的提示模板。应用按需要使用它们，服务器也不必三类都实现。<Cite id="mcp-primitives" /></p><dl className={styles.primitiveList}><div><Wrench size={25} /><dt>Tools</dt><dd>调用 <code>read_log(path)</code>，执行一次日志读取。</dd></div><div><FileText size={25} /><dt>Resources</dt><dd>读取项目说明，取得可加入上下文的资料。</dd></div><div><Archive size={25} /><dt>Prompts</dt><dd>选用“排查启动失败”模板，再补入本次参数和材料。</dd></div></dl><p>服务器给出资源地址，仍需要应用去读并选择内容；取回模板，也不表示任务已经完成。传过来的信息需要被接入真正的工作过程。</p></ArticleSection>
    <ArticleSection id="boundary" title="连接之后的工作" className={styles.offsetSection}><OldAnchor slug="mcp" part="quiz-heading" /><p id="mcp-boundary" className="vp-citation-target">MCP 约定连接与信息交换，不负责规定模型如何思考，也不替代应用自身的运行逻辑。应用仍要选择材料、调用模型、处理工具结果，并决定继续还是结束。<Cite id="mcp-boundary" /></p><p>在服务排错任务中，MCP 可以连接日志工具；<ConceptTerm slug="agent-harness">Harness</ConceptTerm> 负责把结果放回<ConceptTerm slug="context">上下文</ConceptTerm>，再推进<ConceptTerm slug="agent-loop">循环</ConceptTerm>。不用 MCP 也能接工具；是否采用它，取决于连接与复用的需要。</p><p id="mcp-control" className="vp-citation-target">应用还要处理权限、用户控制与执行记录。MCP 官方文档列出了工具可见性、操作批准和活动日志等控制方式。<strong>采用同一协议，不表示服务器天然可信，也不表示所有操作都已获准。</strong><Cite id="mcp-control" /></p><ArticleAside title="连接可用，调用仍失败"><p>可能是服务器没有提供该工具、参数不符合定义、资源已不存在，或底层系统拒绝访问。先确认失败发生在连接、能力发现还是操作执行，不要把所有错误都归结为模型没有理解提示词。</p></ArticleAside></ArticleSection>
  </ConceptArticle>;
}

export function SandboxTermPage() {
  const Cite = ({ id }: { id: string }) => <ArticleCitation id={id} sources={sandboxSources} />;
  return <ConceptArticle slug="execution-sandbox" title="Sandbox" hero={<SandboxHero />} sources={sandboxSources} sections={[["boundary", "操作能到哪里"], ["dimensions", "目录与网络分别限制"], ["approval", "批准与隔离"], ["limits", "边界内仍要检查"]]} intro={<>执行沙箱为运行中的程序划定可访问的范围。<strong>限制由执行环境落实，而不只是一句写给模型的提醒。</strong>文件、网络和资源能访问多少，取决于实际配置。</>}>
    <ArticleSection id="boundary" title="操作能到哪里"><OldAnchor slug="execution-sandbox" part="definition" /><p id="sandbox-enforcement" className="vp-citation-target">模型提出一个命令后，真正执行它的是程序。沙箱可以在系统层限制这个程序及其子进程的访问范围。Anthropic 的沙箱实践同时控制文件系统与网络，减少操作触及宿主环境的范围。<Cite id="sandbox-enforcement" /></p><p>这里设定：只允许读写工作目录；外部密钥禁止访问；文档站点默认不开放。选择一次操作，看它停在哪里。全部是本地教学模拟，不会读写文件或发出网络请求。</p><OldAnchor slug="execution-sandbox" part="scene-heading" /><SandboxLesson /><p>同一个读取命令，换了目标路径，就可能从允许变成拒绝。判断依据是这次操作、目标和当前规则，而非模型是否声称它“很安全”。</p></ArticleSection>
    <ArticleSection id="dimensions" title="目录与网络分别限制"><OldAnchor slug="execution-sandbox" part="prompt-heading" /><p id="sandbox-dimensions" className="vp-citation-target">只限制网络，不能代替文件访问控制；只限制文件，也不能代替网络访问控制。Anthropic 的实现把两者结合：按目录限制文件操作，通过受控代理限制可连接的站点。具体规则应根据任务配置。<Cite id="sandbox-dimensions" /></p><div className={styles.permissionColumns}><div><FileText size={29} weight="light" /><h3>文件系统</h3><p>哪些目录可读？哪些目录可写？外部凭据是否暴露给进程？</p><code>/workspace</code></div><div><Globe size={29} weight="light" /><h3>网络</h3><p>是否能联网？能访问哪些目标？请求是否经过受控出口？</p><code>docs.example.com</code></div></div><p>演示中，允许访问文档站点不会同时开放外部密钥。真实环境还可能对时间、内存和进程数量设置限制，防止一个任务长期占用资源。</p></ArticleSection>
    <ArticleSection id="approval" title="批准与隔离" className={styles.offsetSection}><p id="sandbox-approval" className="vp-citation-target">操作批准与沙箱隔离承担不同工作。批准决定某个动作是否可以执行；沙箱限制执行时能够触及的资源。在预先限定的范围内，应用可以允许部分操作直接运行，越界请求则按规则停止或进入授权流程。<Cite id="sandbox-approval" /></p><div className={styles.approvalPair}><div><ShieldCheck size={26} /><strong>是否允许这次动作</strong><p>例如，是否允许修改项目文件。</p></div><div><LockSimple size={26} /><strong>执行时能访问哪里</strong><p>即使允许修改，也只能触及许可目录。</p></div></div><p>工具描述和提示词能帮助模型理解边界；实际约束仍应在程序侧落实。遇到拒绝后，应说明需要什么访问权限，或使用现有范围内的办法继续，而非反复换一种命令绕过限制。</p></ArticleSection>
    <ArticleSection id="limits" title="边界内仍要检查"><OldAnchor slug="execution-sandbox" part="quiz-heading" /><p id="sandbox-implementation" className="vp-citation-target">沙箱并不只有一种实现。gVisor 在应用与宿主系统之间提供额外的隔离层；其他方案可能采用系统安全策略或虚拟机。隔离强度、兼容性和开销会不同，不能仅凭“运行在沙箱里”就判断保护程度。<Cite id="sandbox-implementation" /></p><p><strong>允许修改工作区，也意味着错误修改可能发生在工作区内。</strong>沙箱不会自动判断代码是否正确，更不会替你恢复所有改动。服务修好之后，仍要运行检查、查看差异，并保留适当的回滚手段。</p><p>回到 <ConceptTerm slug="agent-harness">Harness</ConceptTerm>：工具提供动作，沙箱限制范围，<ConceptTerm slug="agent-loop">循环</ConceptTerm>根据结果推进任务。边界明确与任务完成，需要各自的证据。</p></ArticleSection>
  </ConceptArticle>;
}
